# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{japaneggae}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["tily"]
  s.date = %q{2010-10-11}
  s.description = %q{自分用日本語処理ライブラリ}
  s.email = %q{tily05@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "Rakefile",
     "VERSION",
     "lib/japaneggae.rb",
     "lib/japaneggae/conjugatable.rb",
     "lib/japaneggae/featured.rb",
     "lib/japaneggae/hatenable.rb",
     "lib/japaneggae/mecabable.rb",
     "spec/featured_spec.rb",
     "spec/japanese_spec.rb",
     "spec/mecabable_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/tily/ruby-japaneggae}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{自分用日本語処理ライブラリ}
  s.test_files = [
    "spec/mecabable_spec.rb",
     "spec/featured_spec.rb",
     "spec/japanese_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

